review:
  approved: false
  reviewer: ''
  note: ''
name: MasatoArima/RadiationTherapyApplication
url: https://github.com/MasatoArima/RadiationTherapyApplication
platform: github
description: ''
license: null
language: Python
keywords: []
stars: 0
updated_at: '2022-01-10T12:16:56Z'
image_source: null
heuristic_total_score: 8
heuristic_reasons:
- Matched 1 strong particle-therapy term(s) in metadata/content.
- Matched 3 support term(s).
readme_excerpt: "# RadiationTherapyApplication\n\npydicom ver : 1.4.2\n\n1. RTplan_information.py\n  \
  \  - Jaw\n    - MLC\n    - MU\n    - Weight\n    - MU/CP\n\n2. MCS.py\n    - vmat_MCS\n\n3. JTCS.py\n\
  \    - JTCS\n"
